name: CI tests

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths:
    - 'src/**'
    - 'spec/**'
    - 'bin/**'
  pull_request:
  workflow_dispatch:

jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm clean-install
      # - name: Lint
      #   run: npm run lint
      - name: Test library
        run: npm run test